//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12
//!
//! 注意：DueDate 字段使用 Option<serde_json::Value> 存储，
//! 但提供了 due_date() 和 set_due_date() 方法进行类型安全的转换

use async_trait::async_trait;
use chrono::NaiveDateTime;
use sea_orm::{DbErr, Set, entity::prelude::*};
use serde::{Deserialize, Serialize};

use crate::objects::DueDate;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "items")]
#[serde(rename_all = "camelCase")]
#[derive(Default)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub content: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,

    /// 截止日期字段，以 JSON 格式存储
    /// 推荐使用 due_date() / set_due_date() 方法进行类型安全操作
    #[sea_orm(column_type = "Json", nullable)]
    pub due: Option<serde_json::Value>,

    pub added_at: NaiveDateTime,
    #[sea_orm(nullable)]
    pub completed_at: Option<NaiveDateTime>,
    pub updated_at: NaiveDateTime,

    #[sea_orm(column_type = "Text", nullable)]
    pub section_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_id: Option<String>,

    pub priority: Option<i32>,
    pub child_order: Option<i32>,
    pub day_order: Option<i32>,
    pub checked: bool,
    pub is_deleted: bool,
    pub collapsed: bool,
    pub pinned: bool,
    #[sea_orm(column_type = "Json", nullable)]
    pub labels: Option<String>,
    #[sea_orm(column_type = "Json", nullable)]
    pub extra_data: Option<serde_json::Value>,
    #[sea_orm(column_type = "Text", nullable)]
    pub item_type: Option<String>,
}

#[derive(Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let mut this = self;
        let now = chrono::Utc::now().naive_utc();

        if insert {
            this.id = Set(Uuid::new_v4().to_string());
            this.added_at = Set(now);
        }

        this.updated_at = Set(now);
        Ok(this)
    }
}

impl Model {
    /// 获取强类型的 DueDate
    pub fn due_date(&self) -> Option<DueDate> {
        self.due.as_ref().and_then(|json| serde_json::from_value(json.clone()).ok())
    }

    /// 设置 DueDate
    ///
    /// # 参数
    /// * `due` - DueDate 对象，传入 None 表示清除截止日期
    pub fn set_due_date(&mut self, due: Option<DueDate>) {
        self.due = due.map(|d| serde_json::to_value(d).unwrap_or_default());
    }

    /// 获取截止日期中的日期时间（便捷方法）
    ///
    /// # 返回
    /// * `Some(NaiveDateTime)` - 如果存在有效的截止日期
    /// * `None` - 如果没有截止日期或解析失败
    pub fn due_datetime(&self) -> Option<NaiveDateTime> {
        self.due_date()?.datetime()
    }

    /// 检查是否已过期
    ///
    /// # 返回
    /// * `true` - 如果截止日期已过
    /// * `false` - 如果没有截止日期或尚未过期
    pub fn is_overdue(&self) -> bool {
        match self.due_datetime() {
            Some(due) => due < chrono::Utc::now().naive_utc(),
            None => false,
        }
    }

    /// 检查是否今天到期
    ///
    /// # 返回
    /// * `true` - 如果截止日期是今天
    /// * `false` - 如果没有截止日期或不是今天
    pub fn is_due_today(&self) -> bool {
        match self.due_datetime() {
            Some(due) => {
                let today = chrono::Utc::now().naive_utc().date();
                due.date() == today
            },
            None => false,
        }
    }

    /// 检查是否为过去日期（超过今天，即昨天及之前）
    ///
    /// # 返回
    /// * `true` - 如果截止日期是昨天或更早
    /// * `false` - 如果没有截止日期或是今天及之后
    pub fn is_past_due(&self) -> bool {
        match self.due_datetime() {
            Some(due) => {
                let today = chrono::Utc::now().naive_utc().date();
                due.date() < today
            },
            None => false,
        }
    }

    // ==================== 字段分组辅助方法 ====================

    /// 获取基础信息字段组
    ///
    /// 包含：id, content, description
    pub fn base_info(&self) -> ItemBaseInfo {
        ItemBaseInfo {
            id: self.id.clone(),
            content: self.content.clone(),
            description: self.description.clone(),
        }
    }

    /// 获取时间字段组
    ///
    /// 包含：added_at, completed_at, updated_at, due
    pub fn time_info(&self) -> ItemTimeInfo {
        ItemTimeInfo {
            added_at: self.added_at,
            completed_at: self.completed_at,
            updated_at: self.updated_at,
            due_date: self.due_date(),
        }
    }

    /// 获取层级关系字段组
    ///
    /// 包含：section_id, project_id, parent_id
    pub fn hierarchy_info(&self) -> ItemHierarchyInfo {
        ItemHierarchyInfo {
            section_id: self.section_id.clone(),
            project_id: self.project_id.clone(),
            parent_id: self.parent_id.clone(),
        }
    }

    /// 获取状态字段组
    ///
    /// 包含：checked, is_deleted, collapsed, pinned
    pub fn status_info(&self) -> ItemStatusInfo {
        ItemStatusInfo {
            checked: self.checked,
            is_deleted: self.is_deleted,
            collapsed: self.collapsed,
            pinned: self.pinned,
        }
    }

    /// 获取排序字段组
    ///
    /// 包含：priority, child_order, day_order
    pub fn order_info(&self) -> ItemOrderInfo {
        ItemOrderInfo {
            priority: self.priority,
            child_order: self.child_order,
            day_order: self.day_order,
        }
    }
}

// ==================== 字段分组结构体 ====================

/// 基础信息字段组
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemBaseInfo {
    pub id: String,
    pub content: String,
    pub description: Option<String>,
}

/// 时间字段组
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemTimeInfo {
    pub added_at: NaiveDateTime,
    pub completed_at: Option<NaiveDateTime>,
    pub updated_at: NaiveDateTime,
    pub due_date: Option<DueDate>,
}

/// 层级关系字段组
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemHierarchyInfo {
    pub section_id: Option<String>,
    pub project_id: Option<String>,
    pub parent_id: Option<String>,
}

/// 状态字段组
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ItemStatusInfo {
    pub checked: bool,
    pub is_deleted: bool,
    pub collapsed: bool,
    pub pinned: bool,
}

/// 排序字段组
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ItemOrderInfo {
    pub priority: Option<i32>,
    pub child_order: Option<i32>,
    pub day_order: Option<i32>,
}
