//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "labels")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub color: Option<String>,
    pub item_order: Option<i32>,
    pub is_deleted: Option<i32>,
    pub is_favorite: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub backend_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
