//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod attachments;
pub mod cur_temp_ids;
pub mod item_labels;
pub mod items;
pub mod labels;
pub mod o_events;
pub mod projects;
pub mod queue;
pub mod reminders;
pub mod sections;
pub mod sources;

// Active domain models
pub use attachments::{ActiveModel as AttachmentActiveModel, Model as AttachmentModel};
pub use item_labels::{ActiveModel as ItemLabelActiveModel, Model as ItemLabelModel};
pub use items::{ActiveModel as ItemActiveModel, Model as ItemModel};
pub use labels::{ActiveModel as LabelActiveModel, Model as LabelModel};
pub use projects::{ActiveModel as ProjectActiveModel, Model as ProjectModel};
pub use reminders::{ActiveModel as ReminderActiveModel, Model as ReminderModel};
pub use sections::{ActiveModel as SectionActiveModel, Model as SectionModel};

// Schema-only leftovers (tables exist; no service path). Kept as modules for codegen/migrations.
