//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12
use async_trait::async_trait;
use sea_orm::{DbErr, Set, entity::prelude::*};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "o_events")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub event_type: Option<String>,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub event_date: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub object_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub object_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub object_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub object_old_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub object_new_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_item_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_project_id: Option<String>,
}

#[derive(Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let mut this = self;
        if insert {
            this.id = Set(Uuid::new_v4().to_string());
        }

        Ok(this)
    }
}
