//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use async_trait::async_trait;
use sea_orm::{entity::prelude::*, DbErr, Set};
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "reminders")]
#[serde(rename_all = "camelCase")]
#[derive(Default)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub notify_uid: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub item_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub service: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reminder_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub due: Option<String>,
    pub mm_offset: Option<i32>,
    pub is_deleted: bool,
}

#[derive(Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::items::Entity",
        from = "Column::ItemId",
        to = "super::items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Items,
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Items.def()
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, db: &C, insert: bool) -> Result<Self, DbErr>
                            where
                                C: ConnectionTrait,
    {
        let mut this = self;
        if insert {
            this.id = Set(Uuid::new_v4().to_string());
        }

        Ok(this)
    }
}
