name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: ""

jobs:
  check:
    name: Format, clippy and test
    runs-on: windows-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Format
        run: cargo +nightly fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D clippy::correctness

      - name: Test
        run: cargo test --workspace --exclude my-test
